"""Repository ports defining interfaces for persistence."""

from typing import Protocol

from embedcraft.domain.entities import (
    Chunk,
    Collection,
    Document,
    IndexRevision,
    Job,
    Project,
    Source,
)


class ProjectRepository(Protocol):
    def create(self, project: Project) -> Project: ...
    def get_by_id(self, project_id: str) -> Project | None: ...
    def get_by_name(self, name: str) -> Project | None: ...
    def list_all(self) -> list[Project]: ...
    def update(self, project: Project) -> Project: ...
    def delete(self, project_id: str) -> bool: ...


class SourceRepository(Protocol):
    def add(self, source: Source) -> Source: ...
    def get_by_id(self, source_id: str) -> Source | None: ...
    def list_by_project(self, project_id: str) -> list[Source]: ...
    def delete(self, source_id: str) -> bool: ...


class DocumentRepository(Protocol):
    def upsert(self, document: Document) -> Document: ...
    def get_by_id(self, document_id: str) -> Document | None: ...
    def get_by_path(self, project_id: str, relative_path: str) -> Document | None: ...
    def list_by_project(self, project_id: str, limit: int = 100, offset: int = 0) -> list[Document]: ...
    def count_by_project(self, project_id: str) -> int: ...
    def get_chunk_by_id(self, chunk_id: str) -> Chunk | None: ...
    def delete(self, document_id: str) -> bool: ...


class CollectionRepository(Protocol):
    def create(self, collection: Collection) -> Collection: ...
    def get_by_id(self, collection_id: str) -> Collection | None: ...
    def list_by_project(self, project_id: str) -> list[Collection]: ...
    def delete(self, collection_id: str) -> bool: ...


class RevisionRepository(Protocol):
    def create(self, revision: IndexRevision) -> IndexRevision: ...
    def get_by_id(self, revision_id: str) -> IndexRevision | None: ...
    def list_by_project(self, project_id: str) -> list[IndexRevision]: ...
    def get_latest_active(self, project_id: str) -> IndexRevision | None: ...
    def update(self, revision: IndexRevision) -> IndexRevision: ...


class JobRepository(Protocol):
    def create(self, job: Job) -> Job: ...
    def get_by_id(self, job_id: str) -> Job | None: ...
    def list_by_project(self, project_id: str) -> list[Job]: ...
    def update(self, job: Job) -> Job: ...
